import { Geist, Geist_Mono, Poppins, Monteserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Amazon Redesign",
  description: "Generated by Federico Bellezza",
  author: "Federico Bellezza",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased Poppins `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
